version: '3.8'

services:

  ####################################### server #############################################

  server:
    container_name: itt-server
    image: node:15.14.0-alpine3.12
    command: "npm run dev -w server"
    ports:
      - 4000:4000
    user: node
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app
    restart: always
