env:
  jest: true
  node: true
parser: "@typescript-eslint/parser"
extends:
  - eslint:recommended
  - plugin:prettier/recommended
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
